//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsw2026Tpi.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dsw2026Tpi.CrossCutting.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno ya fue cancelado o atendido.
        /// </summary>
        public static string APPOINTMENT_ALREADY_CANCELLED {
            get {
                return ResourceManager.GetString("APPOINTMENT_ALREADY_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno fue reservado por otro usuario. Por favor, seleccione otro turno.
        /// </summary>
        public static string APPOINTMENT_CONCURRENCY {
            get {
                return ResourceManager.GetString("APPOINTMENT_CONCURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El motivo debe tener entre 3 y 500 caracteres.
        /// </summary>
        public static string APPOINTMENT_INVALID_REASON {
            get {
                return ResourceManager.GetString("APPOINTMENT_INVALID_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede reservar un turno en una fecha pasada.
        /// </summary>
        public static string APPOINTMENT_PAST_DATE {
            get {
                return ResourceManager.GetString("APPOINTMENT_PAST_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró un paciente con ese DNI.
        /// </summary>
        public static string APPOINTMENT_PATIENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPOINTMENT_PATIENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno seleccionado no está disponible.
        /// </summary>
        public static string APPOINTMENT_SLOT_UNAVAILABLE {
            get {
                return ResourceManager.GetString("APPOINTMENT_SLOT_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        public static string AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requieren permisos para la operación solicitada.
        /// </summary>
        public static string AUTHORIZATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHORIZATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rango horario debe ser múltiplo de 30 minutos y estar alineado a la grilla (:00 o :30).
        /// </summary>
        public static string AVAILABILITY_INVALID_DURATION {
            get {
                return ResourceManager.GetString("AVAILABILITY_INVALID_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mes debe estar entre 1 y 12.
        /// </summary>
        public static string AVAILABILITY_INVALID_MONTH {
            get {
                return ResourceManager.GetString("AVAILABILITY_INVALID_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La hora de inicio debe ser menor a la hora de fin.
        /// </summary>
        public static string AVAILABILITY_INVALID_RANGE {
            get {
                return ResourceManager.GetString("AVAILABILITY_INVALID_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El año no es válido.
        /// </summary>
        public static string AVAILABILITY_INVALID_YEAR {
            get {
                return ResourceManager.GetString("AVAILABILITY_INVALID_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar el mes porque tiene turnos reservados o bloqueados.
        /// </summary>
        public static string AVAILABILITY_MONTH_HAS_BOOKINGS {
            get {
                return ResourceManager.GetString("AVAILABILITY_MONTH_HAS_BOOKINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los rangos horarios se solapan para el mismo médico y día de la semana.
        /// </summary>
        public static string AVAILABILITY_OVERLAP {
            get {
                return ResourceManager.GetString("AVAILABILITY_OVERLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El numero de licencia no puede ser nulo y debe ser menor a 50 caracteres.
        /// </summary>
        public static string DOCTOR_INVALID_LICENSE_NUMBER {
            get {
                return ResourceManager.GetString("DOCTOR_INVALID_LICENSE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe tener entre 3 y 100 caractéres.
        /// </summary>
        public static string DOCTOR_INVALID_NAME {
            get {
                return ResourceManager.GetString("DOCTOR_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Doctor con ese Número de Licencia.
        /// </summary>
        public static string DOCTOR_LICENSE_NUMBER_CONFLICT {
            get {
                return ResourceManager.GetString("DOCTOR_LICENSE_NUMBER_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entidad {0} no se encontró.
        /// </summary>
        public static string ENTITY_NOTFOUND {
            get {
                return ResourceManager.GetString("ENTITY_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI es invalido.
        /// </summary>
        public static string INVALID_DNI {
            get {
                return ResourceManager.GetString("INVALID_DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al registrar el usuario.
        /// </summary>
        public static string REGISTER_USER_CONFLICT {
            get {
                return ResourceManager.GetString("REGISTER_USER_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de registración de usuario no válidos.
        /// </summary>
        public static string REGISTER_USER_INVALID {
            get {
                return ResourceManager.GetString("REGISTER_USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  La descripción debe tener entre 10 y 100 caracteres.
        /// </summary>
        public static string SPECIALITY_INVALID_DESCRIPTION {
            get {
                return ResourceManager.GetString("SPECIALITY_INVALID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe tener entre 3 y 100 caracteres.
        /// </summary>
        public static string SPECIALITY_INVALID_NAME {
            get {
                return ResourceManager.GetString("SPECIALITY_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una especialidad con ese nombre.
        /// </summary>
        public static string SPECIALITY_NAME_CONFLICT {
            get {
                return ResourceManager.GetString("SPECIALITY_NAME_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error no controlado.
        /// </summary>
        public static string UNHANDLED_ERROR {
            get {
                return ResourceManager.GetString("UNHANDLED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más errores de validación ocurrieron.
        /// </summary>
        public static string VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR", resourceCulture);
            }
        }
    }
}
